Milestone 2 Code Review Request
JelilFaisalAbudu/tic_tac_toe_game pull request #4
Opened 2020-05-21 15:46 UTC by JelilFaisalAbudu

- This milestone have been completed and ready for your review.
- The user interface has a welcome message for the player.
- The user is given the option to choose the character/symbol to use in the play.
- There is also a test  to switch between each player.
- All methods to be used to run the game have been commented out.

2020-05-22 00:24 UTC, rOluochKe requested changes
Hello @JelilFaisalAbudu and @Albertino2020 
### Good effort you have put in :clap: However, you have a few issues you need to work on before your project could be approved.
### The logic is still off, you are required to have these functionalities in this milestone(2)
- [ ] game asks players for their names
- [ ] game tells which player turn it is
- [ ] game asks the player to select from available moves
- [ ] game informs player if the selected move is invalid
- [ ] game displays board after the player move
- [ ] game informs player if the selected move is a winning move
- [ ] game informs player if the selected move is a draw move
- [ ] game repeats all actions for the next player's move

### In the logic you have submitted, it lucks a number of behaviors
- it does not ask for my name
- it does not reject invalid data and ask me to put in a valid data
- I cannot win, lose or draw the game
- When I play, the board is not changing, accepting the inputs
![game](https://user-images.githubusercontent.com/8114528/82618431-b8df3380-9bdb-11ea-9d02-da8f37b107b8.png)


### Make all these changes and submit for another code review. Good luck.
- Happy coding!

By Raymond
slack @iamraymond

2020-05-25 10:09 UTC, JelilFaisalAbudu commented
# Milestone 2 2nd code Review Request
- All the required changes requested by the TSE in the previous code review have been effected and ready to for another review.
- Player can choose between letter "X" or "O" to play with.
- The game board is now displaying for each player's move.
- The validity of the player's move is added.

2020-05-25 12:19 UTC, lekegitrepo commented
#### Hi @JelilFaisalAbudu and @Albertino2020 :clap: :clap:
#### Well done. However, the game is still the same as mentioned in the previous review.
#### Please, implement the required changes mentioned by the last reviewer and submit for another review.

### Reviewed by Temitayo Adeleke.

2020-05-25 12:20 UTC, lekegitrepo requested changes
#### Status: Request changes.

2020-05-25 15:11 UTC, JelilFaisalAbudu commented
# Code Review Request
- The changes requested by the TSE before the current TSE's request have already been made.
- I think that there is a technical challenge with the system that was making my latest changes not to be reflected in the repository. But after cross checking, everything is in the respective branch(user_interface) from which I made the pull request.

2020-05-25 16:27 UTC, shshamim63 requested changes
## Status :racing_car: Required Changes :recycle: 
___
Hi @JelilFaisalAbudu and @Albertino2020 :wave: 
Almost covered all the changes asked by the previous reviewer. Just a simple issue is blocking me to approve it right now. Let's check it.
___
### :spades: Mandatory Changes :spades: 
___
- I can not see any message or comment related to winning status or a draw status. You don't to place all the logic in this milestone so a simple puts or comment is enough.
___
##### Please fix the above-mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-05-25 16:27 UTC, shshamim63 commented on bin/main.rb
> +                end
[Optional]
There is another approach to declare it.
input_symb2 = input_symb1 == 'O' ? 'X' : 'O'

2020-05-25 16:27 UTC, shshamim63 commented on bin/main.rb
> +  while count < 9 && !winner
:warning: Comparing with a sudden number indicates that there is a problem based on scalability and feasibility. These are also the terms of single responsibility principles. I think you don't have the intension to use this condition on your game logic milestone.

2020-05-25 20:18 UTC, JelilFaisalAbudu commented
# Review Request
- Comments have been added to show where check for winning status and also a draw status.

2020-05-25 21:28 UTC, pelzolga123 approved these changes
Approved.

2020-05-25 21:29 UTC, pelzolga123 commented
## Good job :+1: Project Approved.
You did all changes required previously. Go ahead and merge to develop.
_Goodluck in your next project_ *Happy coding*

2020-05-29 17:19 UTC, merged